<?php
/**
 * Plain text email newsletter template.
 *
 * Variables available:
 * - $content: The digest content (HTML)
 * - $feed: The feed link object
 *
 * @package AIFeedDigest
 */

// Prevent direct access.
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

$site_name  = get_bloginfo( 'name' );
$site_url   = home_url();
$feed_name  = $feed->link_name ?? __( 'Feed Digest', 'ai-feed-digest' );

// Convert HTML content to plain text.
$plain_content = $content;

// Convert links to text format.
$plain_content = preg_replace( '/<a\s+href=["\']([^"\']+)["\'][^>]*>([^<]+)<\/a>/i', '$2 ($1)', $plain_content );

// Convert headers.
$plain_content = preg_replace( '/<h1[^>]*>(.*?)<\/h1>/i', "\n\n=== $1 ===\n\n", $plain_content );
$plain_content = preg_replace( '/<h2[^>]*>(.*?)<\/h2>/i', "\n\n--- $1 ---\n\n", $plain_content );
$plain_content = preg_replace( '/<h3[^>]*>(.*?)<\/h3>/i', "\n\n$1\n", $plain_content );
$plain_content = preg_replace( '/<h[4-6][^>]*>(.*?)<\/h[4-6]>/i', "\n$1\n", $plain_content );

// Convert line breaks and paragraphs.
$plain_content = preg_replace( '/<br\s*\/?>/i', "\n", $plain_content );
$plain_content = preg_replace( '/<\/p>/i', "\n\n", $plain_content );
$plain_content = preg_replace( '/<p[^>]*>/i', '', $plain_content );

// Convert lists.
$plain_content = preg_replace( '/<li[^>]*>/i', "  * ", $plain_content );
$plain_content = preg_replace( '/<\/li>/i', "\n", $plain_content );
$plain_content = preg_replace( '/<\/?[uo]l[^>]*>/i', "\n", $plain_content );

// Convert horizontal rules.
$plain_content = preg_replace( '/<hr\s*\/?>/i', "\n----------------------------------------\n", $plain_content );

// Convert blockquotes.
$plain_content = preg_replace( '/<blockquote[^>]*>(.*?)<\/blockquote>/is', "\n> $1\n", $plain_content );

// Convert strong/bold.
$plain_content = preg_replace( '/<(strong|b)[^>]*>(.*?)<\/(strong|b)>/i', '*$2*', $plain_content );

// Convert emphasis/italic.
$plain_content = preg_replace( '/<(em|i)[^>]*>(.*?)<\/(em|i)>/i', '_$2_', $plain_content );

// Strip remaining HTML.
$plain_content = wp_strip_all_tags( $plain_content );

// Clean up whitespace.
$plain_content = preg_replace( '/[ \t]+/', ' ', $plain_content );
$plain_content = preg_replace( '/\n{3,}/', "\n\n", $plain_content );
$plain_content = trim( $plain_content );

// Output the plain text email.
echo esc_html( $feed_name ) . "\n";
echo esc_html( wp_date( get_option( 'date_format' ) ) ) . "\n";
echo "========================================\n\n";

echo $plain_content; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Already processed.

echo "\n\n";
echo "----------------------------------------\n";
printf(
	/* translators: %s: site name */
	esc_html__( 'Sent from %s', 'ai-feed-digest' ),
	esc_html( $site_name )
);
echo "\n";
echo esc_url( $site_url );
echo "\n\n";
esc_html_e( 'This digest was generated by AI Feed Digest.', 'ai-feed-digest' );
